#! /bin/bash

unset PYTHONPATH

unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
unset AWS_STORAGE_BUCKET_NAME

unset DATABASE_URL

unset DJANGO_DEBUG
unset DJANGO_SERVE_STATIC
unset DJANGO_SERVE_MEDIA