#! /bin/bash

unset PYTHONPATH

unset DJANGO_SETTINGS_MODULE
unset DJANGO_SECRET_KEY
unset DJANGO_DEBUG
unset DJANGO_SERVE_STATIC
unset DJANGO_SERVE_MEDIA

unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
unset AWS_STORAGE_BUCKET_NAME

unset DATABASE_URL
